export const CONFIG = {
  POLL_INTERVAL_MS: 3000,
  REPLAY_EXISTING: false,
  COUNTDOWN_SEC: 7200,
  MAE_THRESHOLDS: [15, 10, 5],
  ESTIMATOR_MILESTONES: [10, 20, 50],
  STREAK_WINDOW_MS: 300000,
  STREAK_MIN: 3,
  FEED_VISIBLE: 14,
  SPARKLINE_POINTS: 10,
  TOP_MODELS: 6,
  PROJECT_TO_TEAM: {
    pression: 'Team Pression',
    'vfm-pression': 'Team Pression',
    debit: 'Team Débit',
    'vfm-debit': 'Team Débit',
    vanne: 'Team Vanne',
    'vfm-vanne': 'Team Vanne',
    choke: 'Team Choke',
    'vfm-choke': 'Team Choke',
    capteur: 'Team Capteur',
    'vfm-capteur': 'Team Capteur',
  },
  TEAM_LLMS: {
    'Team Pression': 'claude-opus-4.5',
    'Team Débit': 'gpt-5-codex',
    'Team Vanne': 'claude-sonnet-4.5',
    'Team Choke': 'qwen3-coder-480b',
    'Team Capteur': 'gemini-2.5-pro',
  },
  TEAMS: [
    'Team Pression',
    'Team Débit',
    'Team Vanne',
    'Team Choke',
    'Team Capteur',
  ],
  SKILLS: [
    'iterate-from-skore',
    'evaluate-ml-pipeline',
    'iterate-from-user',
    'build-ml-pipeline',
    'audit-ml-pipeline',
    'test-ml-pipeline',
    'smoke-test-ml-pipeline',
  ],
  MODELS: [
    'RandomForestRegressor',
    'GradientBoostingRegressor',
    'ExtraTreesRegressor',
    'HistGradientBoostingRegressor',
    'Ridge',
    'ElasticNet',
    'SVR',
    'KNeighborsRegressor',
    'MLPRegressor',
    'AdaBoostRegressor',
  ],
  TRANSFORMERS: [
    'TableVectorizer',
    'StandardScaler',
    'MinMaxScaler',
    'RobustScaler',
    'PolynomialFeatures',
    'SimpleImputer',
    'QuantileTransformer',
  ],
  ESTIMATOR_SUFFIXES: [
    'RandomForestRegressor',
    'GradientBoostingRegressor',
    'Ridge',
    'ElasticNet',
    'SVR',
    'ExtraTreesRegressor',
    'HistGradientBoostingRegressor',
    'KNeighborsRegressor',
    'MLPRegressor',
    'AdaBoostRegressor',
  ],
};

export const PROBABL_WORDMARK_URL =
  'https://cdn.prod.website-files.com/69dcdbceda2296885506eea4/69ee669dda802928688b7b3e_logo-probabl%20(2).svg';

export const USE_SIMULATION = import.meta.env.VITE_USE_SIMULATION !== 'false';
